server:
  port: 8080

spring:
  application:
    name: pipeline-gateway
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
        import-check:
          enabled: false
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: pipeline-auth
          uri: http://127.0.0.1:9300
          predicates:
            - Path=/auth/**
        - id: pipeline-system
          uri: http://127.0.0.1:9201
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        - id: pipeline-data
          uri: http://127.0.0.1:9400
          predicates:
            - Path=/data/**
          filters:
            - StripPrefix=1
        - id: pipeline-calculation
          uri: http://127.0.0.1:9500
          predicates:
            - Path=/calculation/**
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 10s
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms

sa-token:
  token-name: satoken
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: false

logging:
  level:
    com.pipeline.gateway: debug
